development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :domain: "gmail.com"
  :user_name: "fileshare597"
  :password: "swapneel"
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :domain: "gmail.com"
  :user_name: "fileshare597"
  :password: "swapneel"
  :enable_starttls_auto: true